### ISSUE TITLE
gen_cesm2_omip_IC.ipynb erroneously sets DOC to DOCtot

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/marbl-forcing#6]
The `DOC` values in the file generated by initial_conditions/gen_cesm2_omip_IC.ipynb appear to be equal to `DOCtot`. That is, `DOCr` values have been added to `DOC`.

I'm guessing that the problematic code is cell `In [11]` of initial_conditions/gen_cesm2_omip_IC.ipynb:
```
DOCtot = ds_out['DOC']
DOCtot.values = ds_out['DOC'].values + ds_out['DOCr'].values
DOCtot.attrs['long_name'] = 'DOC + DOCr'
ds_out['DOCtot'] = DOCtot
```
and that this is changing the value of `ds_out['DOC']`, which was not intended.

**Comment by matt-long** [comment]
The first line looks to be setting a pointer to `ds_out.DOC`. That line should probably read
```python
DOCtot = ds_out.DOC.copy()
```
or 
```python
DOCtot = xr.full_like(ds_out.DOC, fill_value=0.)
```
